/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.firkin.kstreams.normalizer.errors.v1.avsc;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Example Error Model which comes from a sink system. This error comes from a Sink which reads from a Topic, using the record to perform an action. */
@org.apache.avro.specific.AvroGenerated
public class ExampleTwoError extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4277479918742565666L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExampleTwoError\",\"namespace\":\"io.firkin.kstreams.normalizer.errors.v1.avsc\",\"doc\":\"Example Error Model which comes from a sink system. This error comes from a Sink which reads from a Topic, using the record to perform an action.\",\"fields\":[{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"The timestamp of when the error occurred, in Unix epoch time UTC (required)\"},{\"name\":\"correlation_id\",\"type\":\"string\",\"doc\":\"Unique id for event tracing\"},{\"name\":\"environment_id\",\"type\":[\"null\",\"string\"],\"doc\":\"Environment where the error took place (optional)\",\"default\":null},{\"name\":\"application_id\",\"type\":[\"null\",\"string\"],\"doc\":\"Application where the error took place (optional)\",\"default\":null},{\"name\":\"instance_id\",\"type\":[\"null\",\"string\"],\"doc\":\"Instance where the error took place (optional)\",\"default\":null},{\"name\":\"metadata\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\",\"default\":null}],\"doc\":\"Metadata from the source system (optional)\",\"default\":null},{\"name\":\"data\",\"type\":[\"null\",\"bytes\"],\"doc\":\"Data from the source system (optional)\",\"default\":null},{\"name\":\"source_message\",\"type\":\"string\",\"doc\":\"Message that caused the error\"},{\"name\":\"source_message_schema_name\",\"type\":\"string\",\"doc\":\"Schema name of the source message\"},{\"name\":\"source_message_offset\",\"type\":\"int\",\"doc\":\"Offset of the source message\"},{\"name\":\"source_message_partition\",\"type\":\"int\",\"doc\":\"Partition of the source message\"},{\"name\":\"source_topic\",\"type\":\"string\",\"doc\":\"Name of the topic the message was consumed from\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ExampleTwoError> ENCODER =
      new BinaryMessageEncoder<ExampleTwoError>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ExampleTwoError> DECODER =
      new BinaryMessageDecoder<ExampleTwoError>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ExampleTwoError> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ExampleTwoError> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ExampleTwoError> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ExampleTwoError>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ExampleTwoError to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ExampleTwoError from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ExampleTwoError instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ExampleTwoError fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The timestamp of when the error occurred, in Unix epoch time UTC (required) */
   private java.time.Instant timestamp;
  /** Unique id for event tracing */
   private java.lang.CharSequence correlation_id;
  /** Environment where the error took place (optional) */
   private java.lang.CharSequence environment_id;
  /** Application where the error took place (optional) */
   private java.lang.CharSequence application_id;
  /** Instance where the error took place (optional) */
   private java.lang.CharSequence instance_id;
  /** Metadata from the source system (optional) */
   private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;
  /** Data from the source system (optional) */
   private java.nio.ByteBuffer data;
  /** Message that caused the error */
   private java.lang.CharSequence source_message;
  /** Schema name of the source message */
   private java.lang.CharSequence source_message_schema_name;
  /** Offset of the source message */
   private int source_message_offset;
  /** Partition of the source message */
   private int source_message_partition;
  /** Name of the topic the message was consumed from */
   private java.lang.CharSequence source_topic;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExampleTwoError() {}

  /**
   * All-args constructor.
   * @param timestamp The timestamp of when the error occurred, in Unix epoch time UTC (required)
   * @param correlation_id Unique id for event tracing
   * @param environment_id Environment where the error took place (optional)
   * @param application_id Application where the error took place (optional)
   * @param instance_id Instance where the error took place (optional)
   * @param metadata Metadata from the source system (optional)
   * @param data Data from the source system (optional)
   * @param source_message Message that caused the error
   * @param source_message_schema_name Schema name of the source message
   * @param source_message_offset Offset of the source message
   * @param source_message_partition Partition of the source message
   * @param source_topic Name of the topic the message was consumed from
   */
  public ExampleTwoError(java.time.Instant timestamp, java.lang.CharSequence correlation_id, java.lang.CharSequence environment_id, java.lang.CharSequence application_id, java.lang.CharSequence instance_id, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata, java.nio.ByteBuffer data, java.lang.CharSequence source_message, java.lang.CharSequence source_message_schema_name, java.lang.Integer source_message_offset, java.lang.Integer source_message_partition, java.lang.CharSequence source_topic) {
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.correlation_id = correlation_id;
    this.environment_id = environment_id;
    this.application_id = application_id;
    this.instance_id = instance_id;
    this.metadata = metadata;
    this.data = data;
    this.source_message = source_message;
    this.source_message_schema_name = source_message_schema_name;
    this.source_message_offset = source_message_offset;
    this.source_message_partition = source_message_partition;
    this.source_topic = source_topic;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return timestamp;
    case 1: return correlation_id;
    case 2: return environment_id;
    case 3: return application_id;
    case 4: return instance_id;
    case 5: return metadata;
    case 6: return data;
    case 7: return source_message;
    case 8: return source_message_schema_name;
    case 9: return source_message_offset;
    case 10: return source_message_partition;
    case 11: return source_topic;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: timestamp = (java.time.Instant)value$; break;
    case 1: correlation_id = (java.lang.CharSequence)value$; break;
    case 2: environment_id = (java.lang.CharSequence)value$; break;
    case 3: application_id = (java.lang.CharSequence)value$; break;
    case 4: instance_id = (java.lang.CharSequence)value$; break;
    case 5: metadata = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 6: data = (java.nio.ByteBuffer)value$; break;
    case 7: source_message = (java.lang.CharSequence)value$; break;
    case 8: source_message_schema_name = (java.lang.CharSequence)value$; break;
    case 9: source_message_offset = (java.lang.Integer)value$; break;
    case 10: source_message_partition = (java.lang.Integer)value$; break;
    case 11: source_topic = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The timestamp of when the error occurred, in Unix epoch time UTC (required)
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * The timestamp of when the error occurred, in Unix epoch time UTC (required)
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'correlation_id' field.
   * @return Unique id for event tracing
   */
  public java.lang.CharSequence getCorrelationId() {
    return correlation_id;
  }


  /**
   * Sets the value of the 'correlation_id' field.
   * Unique id for event tracing
   * @param value the value to set.
   */
  public void setCorrelationId(java.lang.CharSequence value) {
    this.correlation_id = value;
  }

  /**
   * Gets the value of the 'environment_id' field.
   * @return Environment where the error took place (optional)
   */
  public java.lang.CharSequence getEnvironmentId() {
    return environment_id;
  }


  /**
   * Sets the value of the 'environment_id' field.
   * Environment where the error took place (optional)
   * @param value the value to set.
   */
  public void setEnvironmentId(java.lang.CharSequence value) {
    this.environment_id = value;
  }

  /**
   * Gets the value of the 'application_id' field.
   * @return Application where the error took place (optional)
   */
  public java.lang.CharSequence getApplicationId() {
    return application_id;
  }


  /**
   * Sets the value of the 'application_id' field.
   * Application where the error took place (optional)
   * @param value the value to set.
   */
  public void setApplicationId(java.lang.CharSequence value) {
    this.application_id = value;
  }

  /**
   * Gets the value of the 'instance_id' field.
   * @return Instance where the error took place (optional)
   */
  public java.lang.CharSequence getInstanceId() {
    return instance_id;
  }


  /**
   * Sets the value of the 'instance_id' field.
   * Instance where the error took place (optional)
   * @param value the value to set.
   */
  public void setInstanceId(java.lang.CharSequence value) {
    this.instance_id = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return Metadata from the source system (optional)
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
    return metadata;
  }


  /**
   * Sets the value of the 'metadata' field.
   * Metadata from the source system (optional)
   * @param value the value to set.
   */
  public void setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.metadata = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return Data from the source system (optional)
   */
  public java.nio.ByteBuffer getData() {
    return data;
  }


  /**
   * Sets the value of the 'data' field.
   * Data from the source system (optional)
   * @param value the value to set.
   */
  public void setData(java.nio.ByteBuffer value) {
    this.data = value;
  }

  /**
   * Gets the value of the 'source_message' field.
   * @return Message that caused the error
   */
  public java.lang.CharSequence getSourceMessage() {
    return source_message;
  }


  /**
   * Sets the value of the 'source_message' field.
   * Message that caused the error
   * @param value the value to set.
   */
  public void setSourceMessage(java.lang.CharSequence value) {
    this.source_message = value;
  }

  /**
   * Gets the value of the 'source_message_schema_name' field.
   * @return Schema name of the source message
   */
  public java.lang.CharSequence getSourceMessageSchemaName() {
    return source_message_schema_name;
  }


  /**
   * Sets the value of the 'source_message_schema_name' field.
   * Schema name of the source message
   * @param value the value to set.
   */
  public void setSourceMessageSchemaName(java.lang.CharSequence value) {
    this.source_message_schema_name = value;
  }

  /**
   * Gets the value of the 'source_message_offset' field.
   * @return Offset of the source message
   */
  public int getSourceMessageOffset() {
    return source_message_offset;
  }


  /**
   * Sets the value of the 'source_message_offset' field.
   * Offset of the source message
   * @param value the value to set.
   */
  public void setSourceMessageOffset(int value) {
    this.source_message_offset = value;
  }

  /**
   * Gets the value of the 'source_message_partition' field.
   * @return Partition of the source message
   */
  public int getSourceMessagePartition() {
    return source_message_partition;
  }


  /**
   * Sets the value of the 'source_message_partition' field.
   * Partition of the source message
   * @param value the value to set.
   */
  public void setSourceMessagePartition(int value) {
    this.source_message_partition = value;
  }

  /**
   * Gets the value of the 'source_topic' field.
   * @return Name of the topic the message was consumed from
   */
  public java.lang.CharSequence getSourceTopic() {
    return source_topic;
  }


  /**
   * Sets the value of the 'source_topic' field.
   * Name of the topic the message was consumed from
   * @param value the value to set.
   */
  public void setSourceTopic(java.lang.CharSequence value) {
    this.source_topic = value;
  }

  /**
   * Creates a new ExampleTwoError RecordBuilder.
   * @return A new ExampleTwoError RecordBuilder
   */
  public static io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder newBuilder() {
    return new io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder();
  }

  /**
   * Creates a new ExampleTwoError RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ExampleTwoError RecordBuilder
   */
  public static io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder newBuilder(io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder other) {
    if (other == null) {
      return new io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder();
    } else {
      return new io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder(other);
    }
  }

  /**
   * Creates a new ExampleTwoError RecordBuilder by copying an existing ExampleTwoError instance.
   * @param other The existing instance to copy.
   * @return A new ExampleTwoError RecordBuilder
   */
  public static io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder newBuilder(io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError other) {
    if (other == null) {
      return new io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder();
    } else {
      return new io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder(other);
    }
  }

  /**
   * RecordBuilder for ExampleTwoError instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExampleTwoError>
    implements org.apache.avro.data.RecordBuilder<ExampleTwoError> {

    /** The timestamp of when the error occurred, in Unix epoch time UTC (required) */
    private java.time.Instant timestamp;
    /** Unique id for event tracing */
    private java.lang.CharSequence correlation_id;
    /** Environment where the error took place (optional) */
    private java.lang.CharSequence environment_id;
    /** Application where the error took place (optional) */
    private java.lang.CharSequence application_id;
    /** Instance where the error took place (optional) */
    private java.lang.CharSequence instance_id;
    /** Metadata from the source system (optional) */
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;
    /** Data from the source system (optional) */
    private java.nio.ByteBuffer data;
    /** Message that caused the error */
    private java.lang.CharSequence source_message;
    /** Schema name of the source message */
    private java.lang.CharSequence source_message_schema_name;
    /** Offset of the source message */
    private int source_message_offset;
    /** Partition of the source message */
    private int source_message_partition;
    /** Name of the topic the message was consumed from */
    private java.lang.CharSequence source_topic;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.correlation_id)) {
        this.correlation_id = data().deepCopy(fields()[1].schema(), other.correlation_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.environment_id)) {
        this.environment_id = data().deepCopy(fields()[2].schema(), other.environment_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.application_id)) {
        this.application_id = data().deepCopy(fields()[3].schema(), other.application_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.instance_id)) {
        this.instance_id = data().deepCopy(fields()[4].schema(), other.instance_id);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.metadata)) {
        this.metadata = data().deepCopy(fields()[5].schema(), other.metadata);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.data)) {
        this.data = data().deepCopy(fields()[6].schema(), other.data);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.source_message)) {
        this.source_message = data().deepCopy(fields()[7].schema(), other.source_message);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.source_message_schema_name)) {
        this.source_message_schema_name = data().deepCopy(fields()[8].schema(), other.source_message_schema_name);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.source_message_offset)) {
        this.source_message_offset = data().deepCopy(fields()[9].schema(), other.source_message_offset);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.source_message_partition)) {
        this.source_message_partition = data().deepCopy(fields()[10].schema(), other.source_message_partition);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.source_topic)) {
        this.source_topic = data().deepCopy(fields()[11].schema(), other.source_topic);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing ExampleTwoError instance
     * @param other The existing instance to copy.
     */
    private Builder(io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.correlation_id)) {
        this.correlation_id = data().deepCopy(fields()[1].schema(), other.correlation_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.environment_id)) {
        this.environment_id = data().deepCopy(fields()[2].schema(), other.environment_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.application_id)) {
        this.application_id = data().deepCopy(fields()[3].schema(), other.application_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.instance_id)) {
        this.instance_id = data().deepCopy(fields()[4].schema(), other.instance_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.metadata)) {
        this.metadata = data().deepCopy(fields()[5].schema(), other.metadata);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.data)) {
        this.data = data().deepCopy(fields()[6].schema(), other.data);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.source_message)) {
        this.source_message = data().deepCopy(fields()[7].schema(), other.source_message);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.source_message_schema_name)) {
        this.source_message_schema_name = data().deepCopy(fields()[8].schema(), other.source_message_schema_name);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.source_message_offset)) {
        this.source_message_offset = data().deepCopy(fields()[9].schema(), other.source_message_offset);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.source_message_partition)) {
        this.source_message_partition = data().deepCopy(fields()[10].schema(), other.source_message_partition);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.source_topic)) {
        this.source_topic = data().deepCopy(fields()[11].schema(), other.source_topic);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'timestamp' field.
      * The timestamp of when the error occurred, in Unix epoch time UTC (required)
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * The timestamp of when the error occurred, in Unix epoch time UTC (required)
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[0], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * The timestamp of when the error occurred, in Unix epoch time UTC (required)
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * The timestamp of when the error occurred, in Unix epoch time UTC (required)
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearTimestamp() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'correlation_id' field.
      * Unique id for event tracing
      * @return The value.
      */
    public java.lang.CharSequence getCorrelationId() {
      return correlation_id;
    }


    /**
      * Sets the value of the 'correlation_id' field.
      * Unique id for event tracing
      * @param value The value of 'correlation_id'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setCorrelationId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.correlation_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'correlation_id' field has been set.
      * Unique id for event tracing
      * @return True if the 'correlation_id' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'correlation_id' field.
      * Unique id for event tracing
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearCorrelationId() {
      correlation_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'environment_id' field.
      * Environment where the error took place (optional)
      * @return The value.
      */
    public java.lang.CharSequence getEnvironmentId() {
      return environment_id;
    }


    /**
      * Sets the value of the 'environment_id' field.
      * Environment where the error took place (optional)
      * @param value The value of 'environment_id'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setEnvironmentId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.environment_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'environment_id' field has been set.
      * Environment where the error took place (optional)
      * @return True if the 'environment_id' field has been set, false otherwise.
      */
    public boolean hasEnvironmentId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'environment_id' field.
      * Environment where the error took place (optional)
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearEnvironmentId() {
      environment_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'application_id' field.
      * Application where the error took place (optional)
      * @return The value.
      */
    public java.lang.CharSequence getApplicationId() {
      return application_id;
    }


    /**
      * Sets the value of the 'application_id' field.
      * Application where the error took place (optional)
      * @param value The value of 'application_id'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setApplicationId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.application_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'application_id' field has been set.
      * Application where the error took place (optional)
      * @return True if the 'application_id' field has been set, false otherwise.
      */
    public boolean hasApplicationId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'application_id' field.
      * Application where the error took place (optional)
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearApplicationId() {
      application_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'instance_id' field.
      * Instance where the error took place (optional)
      * @return The value.
      */
    public java.lang.CharSequence getInstanceId() {
      return instance_id;
    }


    /**
      * Sets the value of the 'instance_id' field.
      * Instance where the error took place (optional)
      * @param value The value of 'instance_id'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setInstanceId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.instance_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'instance_id' field has been set.
      * Instance where the error took place (optional)
      * @return True if the 'instance_id' field has been set, false otherwise.
      */
    public boolean hasInstanceId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'instance_id' field.
      * Instance where the error took place (optional)
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearInstanceId() {
      instance_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * Metadata from the source system (optional)
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * Metadata from the source system (optional)
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.metadata = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * Metadata from the source system (optional)
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'metadata' field.
      * Metadata from the source system (optional)
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * Data from the source system (optional)
      * @return The value.
      */
    public java.nio.ByteBuffer getData() {
      return data;
    }


    /**
      * Sets the value of the 'data' field.
      * Data from the source system (optional)
      * @param value The value of 'data'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setData(java.nio.ByteBuffer value) {
      validate(fields()[6], value);
      this.data = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * Data from the source system (optional)
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'data' field.
      * Data from the source system (optional)
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearData() {
      data = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'source_message' field.
      * Message that caused the error
      * @return The value.
      */
    public java.lang.CharSequence getSourceMessage() {
      return source_message;
    }


    /**
      * Sets the value of the 'source_message' field.
      * Message that caused the error
      * @param value The value of 'source_message'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setSourceMessage(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.source_message = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'source_message' field has been set.
      * Message that caused the error
      * @return True if the 'source_message' field has been set, false otherwise.
      */
    public boolean hasSourceMessage() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'source_message' field.
      * Message that caused the error
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearSourceMessage() {
      source_message = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'source_message_schema_name' field.
      * Schema name of the source message
      * @return The value.
      */
    public java.lang.CharSequence getSourceMessageSchemaName() {
      return source_message_schema_name;
    }


    /**
      * Sets the value of the 'source_message_schema_name' field.
      * Schema name of the source message
      * @param value The value of 'source_message_schema_name'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setSourceMessageSchemaName(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.source_message_schema_name = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'source_message_schema_name' field has been set.
      * Schema name of the source message
      * @return True if the 'source_message_schema_name' field has been set, false otherwise.
      */
    public boolean hasSourceMessageSchemaName() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'source_message_schema_name' field.
      * Schema name of the source message
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearSourceMessageSchemaName() {
      source_message_schema_name = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'source_message_offset' field.
      * Offset of the source message
      * @return The value.
      */
    public int getSourceMessageOffset() {
      return source_message_offset;
    }


    /**
      * Sets the value of the 'source_message_offset' field.
      * Offset of the source message
      * @param value The value of 'source_message_offset'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setSourceMessageOffset(int value) {
      validate(fields()[9], value);
      this.source_message_offset = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'source_message_offset' field has been set.
      * Offset of the source message
      * @return True if the 'source_message_offset' field has been set, false otherwise.
      */
    public boolean hasSourceMessageOffset() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'source_message_offset' field.
      * Offset of the source message
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearSourceMessageOffset() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'source_message_partition' field.
      * Partition of the source message
      * @return The value.
      */
    public int getSourceMessagePartition() {
      return source_message_partition;
    }


    /**
      * Sets the value of the 'source_message_partition' field.
      * Partition of the source message
      * @param value The value of 'source_message_partition'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setSourceMessagePartition(int value) {
      validate(fields()[10], value);
      this.source_message_partition = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'source_message_partition' field has been set.
      * Partition of the source message
      * @return True if the 'source_message_partition' field has been set, false otherwise.
      */
    public boolean hasSourceMessagePartition() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'source_message_partition' field.
      * Partition of the source message
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearSourceMessagePartition() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'source_topic' field.
      * Name of the topic the message was consumed from
      * @return The value.
      */
    public java.lang.CharSequence getSourceTopic() {
      return source_topic;
    }


    /**
      * Sets the value of the 'source_topic' field.
      * Name of the topic the message was consumed from
      * @param value The value of 'source_topic'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder setSourceTopic(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.source_topic = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'source_topic' field has been set.
      * Name of the topic the message was consumed from
      * @return True if the 'source_topic' field has been set, false otherwise.
      */
    public boolean hasSourceTopic() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'source_topic' field.
      * Name of the topic the message was consumed from
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avsc.ExampleTwoError.Builder clearSourceTopic() {
      source_topic = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ExampleTwoError build() {
      try {
        ExampleTwoError record = new ExampleTwoError();
        record.timestamp = fieldSetFlags()[0] ? this.timestamp : (java.time.Instant) defaultValue(fields()[0]);
        record.correlation_id = fieldSetFlags()[1] ? this.correlation_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.environment_id = fieldSetFlags()[2] ? this.environment_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.application_id = fieldSetFlags()[3] ? this.application_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.instance_id = fieldSetFlags()[4] ? this.instance_id : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.metadata = fieldSetFlags()[5] ? this.metadata : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[5]);
        record.data = fieldSetFlags()[6] ? this.data : (java.nio.ByteBuffer) defaultValue(fields()[6]);
        record.source_message = fieldSetFlags()[7] ? this.source_message : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.source_message_schema_name = fieldSetFlags()[8] ? this.source_message_schema_name : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.source_message_offset = fieldSetFlags()[9] ? this.source_message_offset : (java.lang.Integer) defaultValue(fields()[9]);
        record.source_message_partition = fieldSetFlags()[10] ? this.source_message_partition : (java.lang.Integer) defaultValue(fields()[10]);
        record.source_topic = fieldSetFlags()[11] ? this.source_topic : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ExampleTwoError>
    WRITER$ = (org.apache.avro.io.DatumWriter<ExampleTwoError>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ExampleTwoError>
    READER$ = (org.apache.avro.io.DatumReader<ExampleTwoError>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










