/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bhg.common.errors;
/** Environment where the error took place. */
@org.apache.avro.specific.AvroGenerated
public enum EnvironmentTypes implements org.apache.avro.generic.GenericEnumSymbol<EnvironmentTypes> {
  DEV, QA, STG, PRD, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EnvironmentTypes\",\"namespace\":\"com.bhg.common.errors\",\"doc\":\"Environment where the error took place.\",\"symbols\":[\"DEV\",\"QA\",\"STG\",\"PRD\",\"OTHER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
