/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.firkin.kstreams.normalizer.errors.v1.avdl;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Records and Errors are more-or-less identical, they generate very similar code. In
     Java, error types will extend a Throwable, and include a value + cause in the object.
     The cause is not */
@org.apache.avro.specific.AvroGenerated
public class HelloRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8061622045392156420L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HelloRecord\",\"namespace\":\"io.firkin.kstreams.normalizer.errors.v1.avdl\",\"doc\":\"Records and Errors are more-or-less identical, they generate very similar code. In\\n     Java, error types will extend a Throwable, and include a value + cause in the object.\\n     The cause is not\",\"fields\":[{\"name\":\"message\",\"type\":\"string\",\"doc\":\"Message to send.\",\"default\":\"Hello, World!\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HelloRecord> ENCODER =
      new BinaryMessageEncoder<HelloRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HelloRecord> DECODER =
      new BinaryMessageDecoder<HelloRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HelloRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HelloRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HelloRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<HelloRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HelloRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HelloRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HelloRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HelloRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Message to send. */
   private java.lang.CharSequence message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HelloRecord() {}

  /**
   * All-args constructor.
   * @param message Message to send.
   */
  public HelloRecord(java.lang.CharSequence message) {
    this.message = message;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'message' field.
   * @return Message to send.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * Message to send.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Creates a new HelloRecord RecordBuilder.
   * @return A new HelloRecord RecordBuilder
   */
  public static io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder newBuilder() {
    return new io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder();
  }

  /**
   * Creates a new HelloRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HelloRecord RecordBuilder
   */
  public static io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder newBuilder(io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder other) {
    if (other == null) {
      return new io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder();
    } else {
      return new io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder(other);
    }
  }

  /**
   * Creates a new HelloRecord RecordBuilder by copying an existing HelloRecord instance.
   * @param other The existing instance to copy.
   * @return A new HelloRecord RecordBuilder
   */
  public static io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder newBuilder(io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord other) {
    if (other == null) {
      return new io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder();
    } else {
      return new io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for HelloRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HelloRecord>
    implements org.apache.avro.data.RecordBuilder<HelloRecord> {

    /** Message to send. */
    private java.lang.CharSequence message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing HelloRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'message' field.
      * Message to send.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * Message to send.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * Message to send.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message' field.
      * Message to send.
      * @return This builder.
      */
    public io.firkin.kstreams.normalizer.errors.v1.avdl.HelloRecord.Builder clearMessage() {
      message = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HelloRecord build() {
      try {
        HelloRecord record = new HelloRecord();
        record.message = fieldSetFlags()[0] ? this.message : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HelloRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<HelloRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HelloRecord>
    READER$ = (org.apache.avro.io.DatumReader<HelloRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.message);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










