/*
 * Copyright © 2021 Travis Hoffman (travis@firkin.io)
 * Copyright © 2021 Firkin IO (https://firkin.io/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * The source code in this package has been generated by Avro Maven Generator from a {@code .avdl}
 * file which defines related error records in the Avro Protocol DSL. It may be instructive to compare
 * the classes in this package with those in {@link io.firkin.kstreams.normalizer.errors.v1.avsc}
 * which are materially identical but defined using JSON.
 *
 * The record types include a {@link io.firkin.kstreams.normalizer.errors.v1.avdl.BaseError BaseError}
 * which specifies the minimal common core of error records across a variety of systems.
 */
package io.firkin.kstreams.normalizer.errors.v1.avdl;